name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build-test-staticcheck:
    name: Build, Test, Vet, and Static Analysis
    runs-on: ubuntu-latest
    env:
      GOFLAGS: -mod=readonly
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Verify module tidiness
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum

      - name: Check formatting
        run: |
          fmt_files=$(gofmt -s -l .)
          if [ -n "$fmt_files" ]; then
            echo "The following files are not gofmt-ed:" >&2
            echo "$fmt_files" >&2
            exit 1
          fi

      - name: Vet
        run: go vet ./...

      - name: Build (race)
        run: go build -race ./...

      - name: Test (race + coverage)
        run: go test -race -covermode=atomic -coverprofile=coverage.out ./...

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.out

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: $(go env GOPATH)/bin/staticcheck ./...
