name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    name: Build and Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Vet
        run: go vet ./...

      - name: Install staticcheck
        shell: bash
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Staticcheck (exclude examples)
        shell: bash
        run: |
          set -euo pipefail
          PKGS=$(go list ./... | grep -v /examples)
          if [ -z "$PKGS" ]; then
            echo "No packages to check"
            exit 0
          fi
          staticcheck $PKGS

      - name: Build CLI
        run: go build -trimpath -ldflags "-s -w" -o /tmp/freader ./cmd/freader

      - name: Run tests (exclude examples)
        shell: bash
        run: |
          set -euo pipefail
          PKGS=$(go list ./... | grep -v /examples)
          if [ -z "$PKGS" ]; then
            echo "No packages to test"
            exit 0
          fi
          go test -race -covermode=atomic -coverprofile="coverage.out" $PKGS

      - name: Show coverage summary
        run: go tool cover -func=coverage.out | tail -n 1

      - name: Upload coverage artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.os }}
          path: coverage.out

      - name: Extract coverage percentage (ubuntu-latest, push only)
        if: github.event_name == 'push' && matrix.os == 'ubuntu-latest'
        id: coverage
        shell: bash
        run: |
          set -euo pipefail
          LINE=$(go tool cover -func=coverage.out | tail -n 1)
          # Expected format: total:\t(statements)\tNN.N%
          PCT=$(echo "$LINE" | awk '{print $3}')
          PCT_NUM=${PCT%%%}
          # Determine badge color
          if [ "${PCT_NUM%.*}" -ge 80 ]; then COLOR=brightgreen; elif [ "${PCT_NUM%.*}" -ge 60 ]; then COLOR=yellow; else COLOR=red; fi
          echo "COVERAGE=$PCT_NUM" >> "$GITHUB_ENV"
          echo "BADGE_COLOR=$COLOR" >> "$GITHUB_ENV"

      - name: Prepare Shields endpoint JSON (ubuntu-latest, push only)
        if: github.event_name == 'push' && matrix.os == 'ubuntu-latest'
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p shields
          cat > shields/coverage.json <<EOF
          {
            "schemaVersion": 1,
            "label": "coverage",
            "message": "${COVERAGE}%",
            "color": "${BADGE_COLOR}"
          }
          EOF

      - name: Publish Shields to gh-pages (ubuntu-latest, push only)
        if: github.event_name == 'push' && matrix.os == 'ubuntu-latest'
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: shields
          destination_dir: shields
          keep_files: true
          commit_message: "chore(ci): publish coverage endpoint (Shields)"
